export const movieList = [
  {
    category: "Trending Now",
    id: "cat_1",
    movies: [
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 1 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 2 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 3 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 4 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 5 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 6 },
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 7 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 8 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 9 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 10 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 11 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 12 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 13 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 14 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 15 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 16 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 17 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 18 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 19 },
    ]
  },
  {
    category: "Trending Now",
    id: "cat_2",
    movies: [
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 20 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 21 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 22 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 23 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 24 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 25 },
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 26 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 27 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 28 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 29 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 30 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 31 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 32 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 33 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 34 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 35 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 36 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 37 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 38 },
    ]
  },
  {
    category: "Trending Now",
    id: "cat_3",
    movies: [
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 41 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 42 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 43 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 44 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 45 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 46 },
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 47 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 48 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 49 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 50 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 51 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 52 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 53 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 54 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 55 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 56 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 57 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 58 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 59 },
    ]
  },
  {
    category: "Trending Now",
    id: "cat_4",
    movies: [
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 61 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 62 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 63 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 64 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 65 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 66 },
      { name: "Goodbye", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 67 },
      { name: "The Swimmers", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 68 },
      { name: "Grey Man", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 69 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 70 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 71 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 72 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 73 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 74 },
      { name: "Kepp Breathing", image: "/assets/mockData/thumbnails/movie_image_4.jpeg", id: 75 },
      { name: "Vampire Dairies", image: "/assets/mockData/thumbnails/movie_image_5.jpeg", id: 76 },
      { name: "Blood and Water", image: "/assets/mockData/thumbnails/movie_image_1.jpeg", id: 77 },
      { name: "Heart Break High", image: "/assets/mockData/thumbnails/movie_image_2.jpeg", id: 78 },
      { name: "Control Z", image: "/assets/mockData/thumbnails/movie_image_3.jpeg", id: 79 },
    ]
  },
]